from enum import Enum

class SenalTrafico(Enum):
    LIMITE_20 = 0
    LIMITE_30 = 1
    LIMITE_50 = 2
    LIMITE_60 = 3
    LIMITE_70 = 4
    LIMITE_80 = 5
    FIN_LIMITE_80 = 6
    LIMITE_100 = 7
    LIMITE_120 = 8
    PROHIBIDO_ADELANTAR = 9
    PROHIBIDO_ADELANTAR_3_5_TONELADAS = 10
    DERECHO_DE_VIA = 11
    CARRETERA_PRIORITARIA = 12
    DAR_PASO = 13
    ALTO = 14
    PROHIBIDO_VEHICULOS = 15
    PROHIBIDO_VEHICULOS_MAS_3_5_TONELADAS = 16
    PROHIBIDO_EL_PASO = 17
    PRECAUCION_GENERAL = 18
    CURVA_PELIGROSA_IZQUIERDA = 19
    CURVA_PELIGROSA_DERECHA = 20
    CURVA_DOBLE = 21
    CAMINO_IRREGULAR = 22
    CARRETERA_RESBALADIZA = 23
    ESTRECHAMIENTO_DERECHA = 24
    OBRAS_EN_LA_CALZADA = 25
    SEMAFOROS = 26
    PEATONES = 27
    CRUCE_DE_NINOS = 28
    CRUCE_DE_BICICLETAS = 29
    PRECAUCION_HIELO_NIEVE = 30
    CRUCE_DE_ANIMALES = 31
    FIN_LIMITE_VELOCIDAD_ADELANTAMIENTO = 32
    GIRAR_DERECHA = 33
    GIRAR_IZQUIERDA = 34
    SOLO_ADELANTE = 35
    DERECHA_O_FRENTE = 36
    IZQUIERDA_O_FRENTE = 37
    MANTENER_DERECHA = 38
    MANTENER_IZQUIERDA = 39
    ROTONDA_OBLIGATORIA = 40
    FIN_PROHIBIDO_ADELANTAR = 41
    FIN_PROHIBIDO_ADELANTAR_3_5_TONELADAS = 42

    @classmethod
    def obtener_senal(cls, numero):
        for senal in cls:
            if senal.value == numero:
                return senal
        raise ValueError("Número de señal de tráfico inválido")
